name: face_recognition_application
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  provider: ^6.1.2
  dio: ^5.6.0
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  loading_animation_widget: ^1.2.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/icons_app/

    - .env
